"""add image field to user model

Revision ID: 3ccdc2f3a640
Revises: a5014ceb5330
Create Date: 2020-06-26 14:23:02.020114

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3ccdc2f3a640'
down_revision = 'a5014ceb5330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'image')
    # ### end Alembic commands ###
