"""add relations

Revision ID: 89883b4fdedb
Revises: 24be3426ac45
Create Date: 2020-06-17 16:33:22.043542

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '89883b4fdedb'
down_revision = '24be3426ac45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by_user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))
    op.add_column('event', sa.Column('sports_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))
    op.create_foreign_key(None, 'event', 'user', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'event', 'sport', ['sports_id'], ['id'])
    op.add_column('sport', sa.Column('active_members', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    op.add_column('sport', sa.Column('current_events', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    op.create_foreign_key(None, 'sport', 'user', ['active_members'], ['id'])
    op.create_foreign_key(None, 'sport', 'event', ['current_events'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sport', type_='foreignkey')
    op.drop_constraint(None, 'sport', type_='foreignkey')
    op.drop_column('sport', 'current_events')
    op.drop_column('sport', 'active_members')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'sports_id')
    op.drop_column('event', 'created_by_user_id')
    # ### end Alembic commands ###
